server:
  port: 9292

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cil_electric_device_db
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true